# Generated by Django 2.0.3 on 2018-06-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_auto_20180616_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
