# Generated by Django 2.0.3 on 2018-06-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
        ('bill_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='auth_user.User'),
            preserve_default=False,
        ),
    ]
